<a href="https://colab.research.google.com/github/Mo7ammedSalem98/NLP_Tensorflow/blob/main/NLP_in_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Check for GPU

In [1]:
!nvidia-smi -L

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

--2024-05-03 19:59:52--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2024-05-03 19:59:53 (19.8 MB/s) - ‘helper_functions.py’ saved [10246/10246]



In [3]:
#Import series of helper functions
from helper_functions import unzip_data, create_tensorboard_callback, plot_loss_curves, compare_historys

In [4]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

--2024-05-03 20:00:01--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.141.207, 142.251.2.207, 142.250.101.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.141.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.006s  

2024-05-03 20:00:01 (97.3 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



In [5]:
unzip_data('nlp_getting_started.zip')

##Visualizing a text dataset

In [6]:
#Visualize

import pandas as pd
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [7]:
train_df["keyword"][1]

nan

In [8]:
# Shuffle training dataframe
train_df_shuffle = train_df.sample(frac=1, random_state=42)

In [9]:
train_df_shuffle.head(10)

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   
5559  7934    rainstorm                    NaN   
1765  2538    collision                    NaN   
1817  2611      crashed                    NaN   
6810  9756      tragedy        Los Angeles, CA   
4398  6254    hijacking          Athens,Greece   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0  
5559  @Calum5SOS you look like you got caught in a r...       0  
1765  my favorite lady came to our volunteer meeting...       1  
1817  @brianroemmele UX fail of EMV - people want to...       1  
6810  Can't find my ariana grande shirt  this is a f...       0  
4398  The Murderous Story Of America‰Ûªs First Hijac...       1

In [10]:
train_df_shuffle.target.value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [11]:
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [12]:
# How many examples of each class?
train_df.location.value_counts()

location
USA                    104
New York                71
United States           50
London                  45
Canada                  29
                      ... 
Montr̩al, Qu̩bec       1
Montreal                 1
ÌÏT: 6.4682,3.18287      1
Live4Heed??              1
Lincoln                  1
Name: count, Length: 3341, dtype: int64

In [13]:
# How many total samples?
len(train_df), len(test_df)

(7613, 3263)

In [14]:
# Let's visualize some random training examples
import random
random_index = random.randint(0, len(train_df)-5) # Create random indexes not higher than the total number of samples
for row in train_df_shuffle[["text", "target"]][random_index:random_index+5].itertuples():
  _, text, target = row
  print(f"Target: {target}", "(real diaster)" if target > 0 else "(not real diaster)")
  print(f"Text:\n{text}\n")
  print("---\n")

Target: 0 (not real diaster)
Text:
Sundays during football seasonfrom about 9 am - 11 pm women shouldn't even log onshit be a complete war zone

---

Target: 0 (not real diaster)
Text:
17.Beyonce Is my pick for http://t.co/thoYhrHkfJ Fan Army #Beyhive http://t.co/WvJ39a3BGM

---

Target: 0 (not real diaster)
Text:
@YoungHeroesID Lava Blast &amp; Power Red @dieanpink95 @yu_nita99 #PantherAttack

---

Target: 1 (real diaster)
Text:
If I'm also not mistaken we're sitting right next 2 a nuclear reactor. Not smart when we have a cataclysmic event &amp; that reator melts down.

---

Target: 1 (real diaster)
Text:
Suicide Bomber Kills More Than a Dozen in Saudi Mosque: Saudi Arabia have started experiencing some terrorist ... http://t.co/PIoY1O54f4

---



In [15]:
from sklearn.model_selection import train_test_split

In [16]:
train_sentences, val_sentences, train_labels, val_labels = train_test_split(train_df_shuffle["text"].to_numpy(),
                                                                            train_df_shuffle["target"].to_numpy(),
                                                                            test_size=0.1,
                                                                            random_state=42)

In [17]:
# Check the lengths
len(train_sentences), len(train_labels), len(val_sentences), len(val_labels)

(6851, 6851, 762, 762)

In [18]:
#Check the first 10 samples
train_sentences[:10], train_labels[:10]

(array(['@mogacola @zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
        "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
        'Somehow find you and I collide http://t.co/Ee8RpOahPk',
        '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
        '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
        'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
       dtype=object),
 array([0,

## Convert Text into numbers

There are a few ways to do this, namely
* Tokenziation - direct mapping of token ( a token could be a word or a character) to number
* Embedding - create a matrix of  feature vector for each token (the size of the feature vector can be defined and this embedding can be learned)



## Text vectorization (tokenization)

In [19]:
train_sentences[:5]

array(['@mogacola @zamtriossu i screamed after hitting tweet',
       'Imagine getting flattened by Kurt Zouma',
       '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
       "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
       'Somehow find you and I collide http://t.co/Ee8RpOahPk'],
      dtype=object)

In [20]:
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

In [21]:
# Use the default TextVectorization parameters
text_vectorizer = TextVectorization(max_tokens=10000, #How many words in the vocabulary (automatically add <OOV>)
                                    standardize="lower_and_strip_punctuation",
                                    split="whitespace",
                                    ngrams=None, # Create groups of n-words?
                                    output_mode="int", # how to map tokens to numbers
                                    output_sequence_length=None, # How long do you want your sequences to be?
                                    pad_to_max_tokens=True)

In [22]:
len(train_sentences[0].split())

7

In [23]:
len(train_sentences)

6851

In [24]:
# Find the average number of tokens (words) in the training tweets
round(sum([len(i.split()) for i in train_sentences])/len(train_sentences))

15

In [25]:
# Setup text vectorization variables
max_vocab_length = 10000 # max number of words to have in our vocabulary
max_length = 15 #max length our sequences will be (e.g. how many words from a Tweet does a model see?)

In [26]:
text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                    output_mode="int",
                                    output_sequence_length=max_length)

In [27]:
train_sentences[:10], train_labels[:5]

(array(['@mogacola @zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
        "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
        'Somehow find you and I collide http://t.co/Ee8RpOahPk',
        '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
        '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
        'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
       dtype=object),
 array([0,

In [28]:
# Fit the text vectorizer to the training text
text_vectorizer.adapt(train_sentences)

In [29]:
# Create a sample sentence and tokenize it
sample_sentence = ["There's a flood in my street!", "Hello World!"]
text_vectorizer(sample_sentence)

<tf.Tensor: shape=(2, 15), dtype=int64, numpy=
array([[ 264,    3,  232,    4,   13,  698,    0,    0,    0,    0,    0,
           0,    0,    0,    0],
       [1400,  107,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0]])>

In [30]:
# Choose a random sentence from the training dataset and tokenize it
random_sentence = random.choice(train_sentences)
print(f"Orginal Sentence: \n {random_sentence}\
      \n\nVectorized version: ")
text_vectorizer([random_sentence])

Orginal Sentence: 
 VIDEO: Slain Mexican Journalist Unknowingly Predicted His Own Death http://t.co/QxhOwCv16R via @BreitbartNews      

Vectorized version: 


<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[  72, 8431,    1, 3713, 7189, 2789,   79,  730,  154,    1,   49,
           1,    0,    0,    0]])>

In [31]:
# Get the unique words in the vocabulary
words_in_vocab = text_vectorizer.get_vocabulary() # get all of the unique words in our training data
top_5_words = words_in_vocab[:5] # Get the most common words
bottom_5_words = words_in_vocab[-5:] # Get the least common words

In [32]:
print(f"Number of words in vocab: {len(words_in_vocab)}")
print(f"5 most common words: {top_5_words}")
print(f"5 least common words: {bottom_5_words}")

Number of words in vocab: 10000
5 most common words: ['', '[UNK]', 'the', 'a', 'in']
5 least common words: ['pages', 'paeds', 'pads', 'padres', 'paddytomlinson1']


### Creating an Embedding using an Embedding Layer

The parameters we care most about for our embedding layer:
* `input_dim` = the size of our vocabulary
* `ouput_dim` = the size of the output embedding vector, for example, a value of 100 would mean each token gets represented by a vector 100 long
* `input_length` = length of the sequences being passed to the embedding layer

In [33]:
from tensorflow.keras import layers
embedding = layers.Embedding(input_dim=max_vocab_length, # set input shape
                             output_dim=128, # Output shape
                             embeddings_initializer="uniform",
                             input_length=max_length # How long is each input
                             )
embedding

In [34]:
# Get a random sentece from the training set
random_sentence = random.choice(train_sentences)
print(f"Original text:\n {random_sentence}\
        \n\nEmbedded version:")

# Embed the random sentence (turn it into dense vectors of fixed size)
sample_embed = embedding(text_vectorizer([random_sentence]))
sample_embed

Original text:
 @JimMozel puck=flattened ball lol        

Embedded version:


<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[ 0.00628094,  0.00856844,  0.00572335, ..., -0.00548137,
          0.02914525,  0.04096292],
        [ 0.02294471,  0.0042277 ,  0.03187075, ..., -0.01330675,
          0.01209487, -0.01341367],
        [-0.02065417, -0.01400073,  0.01030986, ..., -0.03659136,
         -0.03468567, -0.02887325],
        ...,
        [-0.00284257, -0.01802605,  0.03443892, ...,  0.03225417,
          0.00133227,  0.00232441],
        [-0.00284257, -0.01802605,  0.03443892, ...,  0.03225417,
          0.00133227,  0.00232441],
        [-0.00284257, -0.01802605,  0.03443892, ...,  0.03225417,
          0.00133227,  0.00232441]]], dtype=float32)>

In [35]:
# Check out a single token's embedding
sample_embed[0][0], sample_embed[0][0].shape, random_sentence

(<tf.Tensor: shape=(128,), dtype=float32, numpy=
 array([ 0.00628094,  0.00856844,  0.00572335,  0.01199694, -0.01118352,
        -0.04685978, -0.04066563,  0.03944406,  0.02554237, -0.03725681,
        -0.02407062, -0.03307749,  0.00919521,  0.01715794, -0.00350072,
         0.02594915,  0.02827132, -0.04248316, -0.03456431,  0.01415775,
        -0.00194427, -0.02729223,  0.03064645,  0.04082927, -0.02609704,
        -0.0409912 ,  0.0131326 , -0.01129102, -0.03139558,  0.02567023,
        -0.03741539, -0.0304919 , -0.0417619 ,  0.0129639 ,  0.0070013 ,
        -0.02227685,  0.04584347,  0.00081205, -0.04008243,  0.01263951,
        -0.0412975 ,  0.04620153,  0.04745037,  0.00447983,  0.0358114 ,
        -0.02846599,  0.04099445,  0.02265611,  0.02596349,  0.02483889,
        -0.01776709, -0.02398814,  0.00529069,  0.03355285, -0.03834748,
        -0.00224171, -0.01348291, -0.01074664, -0.0232769 , -0.01044506,
         0.0233945 ,  0.00322113,  0.00963234, -0.02384546,  0.00470052,
  

## Modelling a text dataset (running a series of experiments)

Now we've a got way to turn our text sequences into numbers, it's time to start building a series of modelling experiments.

we'll start with a baseline and move on from there.

* Model 0: Naive Bayes (baseline)
* Model 1: Feed-forward neural network (dense model)
* Model 2: LSTM model (RNN)
* Model 3: GRU model (RNN)
* Model 4: Bidirectional-LSTM model (RNN)
* Model 5: 1D Convolutional Neural Network (CNN)
* Model 6: Tensorflow Hub pretrained Feature Extractor (using Transfer Learning for NLP
* Model 7: Same as model 6 with 10% of training data)

How are we going to apporach all of these?

Use the standard steps in modelling with TensorFlow.
* Create a model
* Build a model
* Fit a model
* Evaluate our model

## Model 0: Getting a baseline

As with all ML modelling experiments, it's important to create a baseling model so you've got a benchmark for feature experiments to build upon.

To create our baseline, we'll use Sklearn's Multinomial Naive Bayes using the TF-IDF formula to convert our words to numbers.

🔑 **Note:** it's common practice to use non-DL algorithms as a baseline because of their speed and then later using DL to see if you can improve upon them.

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

#Create tokenization and modelling pipline
model_0 = Pipeline([
                    ("tfidf", TfidfVectorizer()), # Convert words to numbers using tfidf
                    ("clf", MultinomialNB()) # Model the text
])

# Fit the pipline to the training data
model_0.fit(train_sentences, train_labels)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [37]:
# Evaluate our baseline model
baseline_score = model_0.score(val_sentences, val_labels)
print(f"Our baseline model achieve an accuracy of: {baseline_score*100:.2f}%")

Our baseline model achieve an accuracy of: 79.27%


In [38]:
train_df.target.value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [39]:
# Make predication
baseline_preds = model_0.predict(val_sentences)
baseline_preds[:20]

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1])

In [40]:
train_labels

array([0, 0, 1, ..., 1, 1, 0])

In [41]:
# Function to evaluate: accuracy, precision, recall, f1-score
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results(y_true, y_pred):
  """
  Calculates model accuracy, precision, recall and f1 score of a binary classification model.
  """
  # Calculate model accuracy
  model_accuracy = accuracy_score(y_true, y_pred) * 100
  # Calculate model precision, recall and f1-score using "weighted" average
  model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average="weighted")
  model_results = {"accuracy": model_accuracy,
                   "precision": model_precision,
                   "recall": model_recall,
                   "f1": model_f1}
  return model_results

In [42]:
# Get baseline results
baseline_results = calculate_results(y_true = val_labels,
                                     y_pred = baseline_preds)
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

### Model 1: A simple dense model

In [43]:
# Create a tensorboard callback (need to create a new one for each model)
from helper_functions import create_tensorboard_callback

# Create a directroy to save TensorBoard logs
SAVE_DIR = "model_logs"

In [44]:
# Build model with the Functional API
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype=tf.string) #inputs are 1-dimensional strings
x = text_vectorizer(inputs) # turn the input text into numbers
x = embedding(x) # create an embedding of the numberized inputs
x = layers.GlobalAveragePooling1D(name="global_avg_pool_layer")(x) # condense the feature vector for each token to one vector
# x = layers.GlobalMaxPool1D()(x)
outputs = layers.Dense(1, activation="sigmoid")(x) #create the output layer,
model_1 = tf.keras.Model(inputs, outputs, name="model_1_dense")

In [45]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 global_avg_pool_layer (Glo  (None, 128)               0         
 balAveragePooling1D)                                            
                                                                 
 dense (Dense)               (None, 1)                 129       
                                                                 
Total params: 1280129 (4.88 MB)
Trainable params: 128

In [46]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 global_avg_pool_layer (Glo  (None, 128)               0         
 balAveragePooling1D)                                            
                                                                 
 dense (Dense)               (None, 1)                 129       
                                                                 
Total params: 1280129 (4.88 MB)
Trainable params: 128

In [47]:
# Compile model
model_1.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [48]:
# Fit the model
model_1_history = model_1.fit(x=train_sentences,
                              y=train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels),
                              callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR,
                                                                     experiment_name="model_1_dense")])

Saving TensorBoard log files to: model_logs/model_1_dense/20240503-200005
Epoch 1/5
215/215 [==============================] - 11s 44ms/step - loss: 0.6098 - accuracy: 0.6992 - val_loss: 0.5352 - val_accuracy: 0.7572
Epoch 2/5
215/215 [==============================] - 9s 43ms/step - loss: 0.4399 - accuracy: 0.8194 - val_loss: 0.4714 - val_accuracy: 0.7874
Epoch 3/5
215/215 [==============================] - 9s 43ms/step - loss: 0.3463 - accuracy: 0.8593 - val_loss: 0.4574 - val_accuracy: 0.7940
Epoch 4/5
215/215 [==============================] - 10s 46ms/step - loss: 0.2833 - accuracy: 0.8904 - val_loss: 0.4669 - val_accuracy: 0.7940
Epoch 5/5
215/215 [==============================] - 12s 55ms/step - loss: 0.2366 - accuracy: 0.9139 - val_loss: 0.4807 - val_accuracy: 0.7822


In [49]:
model_1.evaluate(val_sentences, val_labels)

24/24 [==============================] - 0s 4ms/step - loss: 0.4807 - accuracy: 0.7822


[0.4807124137878418, 0.7821522355079651]

In [50]:
# Make some predications and evaluate those
model_1_pred_probs = model_1.predict(val_sentences)
model_1_pred_probs.shape

24/24 [==============================] - 0s 3ms/step


(762, 1)

In [51]:
# Look at a single predication
model_1_pred_probs[0]

array([0.35091594], dtype=float32)

In [52]:
# Look at the first 10 predications
model_1_pred_probs[:10]

array([[0.35091594],
       [0.75100386],
       [0.9981378 ],
       [0.12029564],
       [0.11401203],
       [0.93414694],
       [0.9095327 ],
       [0.993505  ],
       [0.96261334],
       [0.30385938]], dtype=float32)

In [53]:
# Convert model predication probabilities to label format
model_1_preds = tf.squeeze(tf.round(model_1_pred_probs))
model_1_preds[:20]

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1.], dtype=float32)>

In [54]:
# Calculate our model_1 results
model_1_results = calculate_results(y_true=val_labels,
                                    y_pred=model_1_preds)
model_1_results

{'accuracy': 78.21522309711287,
 'precision': 0.7860403042839984,
 'recall': 0.7821522309711286,
 'f1': 0.779380517102918}

In [55]:
import numpy as np
np.array(list(model_1_results.values())) > np.array(list(baseline_results.values()))

array([False, False, False, False])